default:

  interval: 1 # (seconds) interval between hPING requests
  type: HEAD # (type or requests): HEAD, GET, POST, PUT
  timeout: 5000 # (milliseconds) request connection timeout
  use_colors: true # (true || false), use colors for hPING output
  show_stats_for_last: 100 # (number of requests) show hPING statistics for last X number of requests, set 0 to disable
  max_run_time: 600 # (seconds) hPING maximum running time, set 0 to disable

  log_status_change: false # (true || false) if true, hPING will log status changes to log file
  log_file: ./logs/hping.log # (path) to hPING log file
  log_stats_on_exit: true # (true || false) if true, hPING will log statistics to file on exit

  display_in_output: # use true || fasle to turn on/off log output sections
    status: true 
    url: true
    ip: true
    type: false
    status_code: true
    status_info: true
    server: true
    content_length: false
    response_time: true

  servers: # predefined servers groups for use hPING by group name. Usage: hping 'micsrosoft live' || hping 'apple production' || hping eurohosting
    'microsoft live': # microsoft live servers group example
      - http://www.live.com
      - http://www.live.fr
      - http://www.live.de
      - http://www.live.ru
      - http://www.live.com/api
    'apple production': # apple production servers group example
      - http://www.apple.com
      - http://www.icloud.com
      - https://itunes.apple.com
    eurohosting: # popular eurohosting servers group example
      - http://www.leaseweb.eu
      - http://www.hetzner.de
      - http://www.1and1.co.uk
